title:            Imagination
description: >
    out of imagination
url:              # Site url.
signoff:          # Your name.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:sweeliao@163.com
    external:     true
  - name:         GitHub
    url:          http://github.com/liaosiwei
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
